"""Updated program dataset - Research-backed programs from PDF"""
from datetime import datetime, timezone, timedelta

# California Programs
CALIFORNIA_PROGRAMS = [
    # 1. Fresh Rx Produce Prescription Program (Monterey County)
    {
        "program_id": "prog_ca_fresh_rx_monterey",
        "program_name": "Fresh Rx Produce Prescription Program (Everyone's Harvest)",
        "benefit_type": "produce_rx",
        "geo_scope": "county",
        "state": "California",
        "county": "Monterey County",
        "zip_prefixes": None,
        "how_to_apply_url": "https://www.everyonesharvest.org/programs/fresh-rx/enroll-in-fresh-rx/",
        "contact_phone": "831-384-6961",
        "source_urls": ["https://www.everyonesharvest.org/programs/fresh-rx/enroll-in-fresh-rx/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # 2-6. Alliance Community Supports MTM (5 counties)
    {
        "program_id": "prog_ca_alliance_mtm_mariposa",
        "program_name": "Alliance Community Supports: Medically Tailored Meals (Mariposa County)",
        "benefit_type": "mtm",
        "geo_scope": "county",
        "state": "California",
        "county": "Mariposa County",
        "zip_prefixes": None,
        "how_to_apply_url": "https://thealliance.health/for-providers/manage-care/enhanced-care-management-ecm-and-community-supports-provider-referrals/",
        "contact_phone": "800-700-3874",
        "source_urls": ["https://thealliance.health/for-providers/manage-care/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    {
        "program_id": "prog_ca_alliance_mtm_merced",
        "program_name": "Alliance Community Supports: Medically Tailored Meals (Merced County)",
        "benefit_type": "mtm",
        "geo_scope": "county",
        "state": "California",
        "county": "Merced County",
        "zip_prefixes": None,
        "how_to_apply_url": "https://thealliance.health/for-providers/manage-care/enhanced-care-management-ecm-and-community-supports-provider-referrals/",
        "contact_phone": "800-700-3874",
        "source_urls": ["https://thealliance.health/for-providers/manage-care/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    {
        "program_id": "prog_ca_alliance_mtm_monterey",
        "program_name": "Alliance Community Supports: Medically Tailored Meals (Monterey County)",
        "benefit_type": "mtm",
        "geo_scope": "county",
        "state": "California",
        "county": "Monterey County",
        "zip_prefixes": None,
        "how_to_apply_url": "https://thealliance.health/for-providers/manage-care/enhanced-care-management-ecm-and-community-supports-provider-referrals/",
        "contact_phone": "800-700-3874",
        "source_urls": ["https://thealliance.health/for-providers/manage-care/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    {
        "program_id": "prog_ca_alliance_mtm_santa_cruz",
        "program_name": "Alliance Community Supports: Medically Tailored Meals (Santa Cruz County)",
        "benefit_type": "mtm",
        "geo_scope": "county",
        "state": "California",
        "county": "Santa Cruz County",
        "zip_prefixes": None,
        "how_to_apply_url": "https://thealliance.health/for-providers/manage-care/enhanced-care-management-ecm-and-community-supports-provider-referrals/",
        "contact_phone": "800-700-3874",
        "source_urls": ["https://thealliance.health/for-providers/manage-care/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    {
        "program_id": "prog_ca_alliance_mtm_san_benito",
        "program_name": "Alliance Community Supports: Medically Tailored Meals (San Benito County)",
        "benefit_type": "mtm",
        "geo_scope": "county",
        "state": "California",
        "county": "San Benito County",
        "zip_prefixes": None,
        "how_to_apply_url": "https://thealliance.health/for-providers/manage-care/enhanced-care-management-ecm-and-community-supports-provider-referrals/",
        "contact_phone": "800-700-3874",
        "source_urls": ["https://thealliance.health/for-providers/manage-care/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # 7. Market Match (California State-wide)
    {
        "program_id": "prog_ca_market_match",
        "program_name": "Market Match (California)",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "California",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://marketmatch.org/about/how-it-works/",
        "contact_phone": "(510) 925-4001",
        "source_urls": ["https://marketmatch.org/about/how-it-works/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=365),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # 8. CalFresh Fruit & Vegetable EBT Pilot
    {
        "program_id": "prog_ca_calfresh_fv_pilot",
        "program_name": "CalFresh Fruit & Vegetable EBT Pilot Project",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "California",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://www.cdss.ca.gov/inforesources/ebt/california-fruit-vegetable-ebt-pilot-project",
        "contact_phone": "(916) 651-8848",
        "source_urls": ["https://www.cdss.ca.gov/inforesources/ebt/california-fruit-vegetable-ebt-pilot-project"],
        "status": "active",
        "effective_start": datetime(2025, 11, 17, tzinfo=timezone.utc),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
]

# Out-of-State Programs (for reference/comparison)
OTHER_STATE_PROGRAMS = [
    # Washington
    {
        "program_id": "prog_wa_snap_market_match",
        "program_name": "SNAP Market Match (Washington)",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "Washington",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://doh.wa.gov/you-and-your-family/nutrition-and-physical-activity/healthy-eating/snap-match-programs/snap-market-match",
        "contact_phone": "(360) 236-3148",
        "source_urls": ["https://doh.wa.gov/you-and-your-family/nutrition-and-physical-activity/healthy-eating/snap-match-programs/snap-market-match"],
        "status": "active",
        "effective_start": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    {
        "program_id": "prog_wa_snap_produce_match",
        "program_name": "SNAP Produce Match (Washington)",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "Washington",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://doh.wa.gov/you-and-your-family/nutrition-and-physical-activity/healthy-eating/snap-match-programs/snap-produce-match",
        "contact_phone": "(360) 236-3148",
        "source_urls": ["https://doh.wa.gov/you-and-your-family/nutrition-and-physical-activity/healthy-eating/snap-match-programs/snap-produce-match"],
        "status": "active",
        "effective_start": datetime(2025, 10, 1, tzinfo=timezone.utc),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # Colorado
    {
        "program_id": "prog_co_double_up_food_bucks",
        "program_name": "Double Up Food Bucks (Colorado)",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "Colorado",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://doubleupcolorado.org/how-double-up-works/",
        "contact_phone": "720-573-3617",
        "source_urls": ["https://doubleupcolorado.org/how-double-up-works/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=365),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    {
        "program_id": "prog_co_snap_produce_bonus",
        "program_name": "Colorado SNAP Produce Bonus",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "Colorado",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://cdhs.colorado.gov/snap-produce-bonus",
        "contact_phone": "303-866-5700",
        "source_urls": ["https://cdhs.colorado.gov/snap-produce-bonus"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=180),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # Michigan
    {
        "program_id": "prog_mi_double_up_food_bucks",
        "program_name": "Double Up Food Bucks (Michigan)",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "Michigan",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://doubleupfoodbucks.org/how-double-up-works/",
        "contact_phone": "866-586-2796",
        "source_urls": ["https://doubleupfoodbucks.org/how-double-up-works/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=365),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # Oregon
    {
        "program_id": "prog_or_double_up_food_bucks",
        "program_name": "Double Up Food Bucks (Oregon)",
        "benefit_type": "snap_support",
        "geo_scope": "state",
        "state": "Oregon",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://doubleuporegon.org/how-it-works/",
        "contact_phone": "503-208-4495",
        "source_urls": ["https://doubleuporegon.org/how-it-works/"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=365),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # New York
    {
        "program_id": "prog_ny_health_bucks",
        "program_name": "Health Bucks (New York City)",
        "benefit_type": "snap_support",
        "geo_scope": "county",
        "state": "New York",
        "county": "New York City",
        "zip_prefixes": None,
        "how_to_apply_url": "https://www.nyc.gov/site/doh/health/health-topics/health-bucks.page",
        "contact_phone": "347-396-4721",
        "source_urls": ["https://www.nyc.gov/site/doh/health/health-topics/health-bucks.page"],
        "status": "active",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=365),
        "effective_end": None,
        "last_verified_at": datetime.now(timezone.utc),
    },
    
    # North Carolina (PAUSED - include for reference)
    {
        "program_id": "prog_nc_healthy_opportunities",
        "program_name": "Healthy Opportunities Pilots (North Carolina)",
        "benefit_type": "mtm",
        "geo_scope": "state",
        "state": "North Carolina",
        "county": None,
        "zip_prefixes": None,
        "how_to_apply_url": "https://www.ncdhhs.gov/about/department-initiatives/healthy-opportunities/healthy-opportunities-pilots",
        "contact_phone": "888-245-0179",
        "source_urls": ["https://www.ncdhhs.gov/about/department-initiatives/healthy-opportunities/healthy-opportunities-pilots"],
        "status": "paused",
        "effective_start": datetime.now(timezone.utc) - timedelta(days=365),
        "effective_end": datetime(2025, 7, 1, tzinfo=timezone.utc),
        "last_verified_at": datetime.now(timezone.utc),
    },
]

# Combined programs list
ALL_PROGRAMS = CALIFORNIA_PROGRAMS + OTHER_STATE_PROGRAMS

print(f"Total programs: {len(ALL_PROGRAMS)}")
print(f"California programs: {len(CALIFORNIA_PROGRAMS)}")
print(f"Other state programs: {len(OTHER_STATE_PROGRAMS)}")
